/*
  Modul 0 - Einführung in die Ausbildung

  Wir freuen uns sehr, dass Sie den Weg auf die Plattform gefunden haben. Im "Kurs 0" geht es zunächst darum, Sie für die Plattform fit zu machen und Ihnen einige Tipps und Tricks mit auf den Weg zu geben. So wird Ihnen die Arbeit auf der Plattform deutlich mehr Spaß machen...
*/

// Chapters
articles = 
[
  { type: 'chapter', title: '0.1 Herzlich Willkommen', post_content: `<p><img class="alignnone size-full" src="https://happiness-edutainment.de/medien/78.jpg" alt="" /></p>\n<p>Sehen Sie sich bitte zu Beginn dieses Moduls das folgende Video an. Hier wird Ihnen Oliver Haas die ersten Schritte auf der Plattform erläutern.</p>\n<p>Viel Spaß beim Kennenlernen und den nachfolgenden Topics!</p>\n\n\n<figure class="wp-block-embed-vimeo wp-block-embed is-type-video is-provider-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps://vimeo.com/173456380\n</div></figure>\n` },
]
coha.run();

// Articles
articles = 
[
  { title: '0.1.1 Einführung in die Ausbildung', post_content: `<img src="https://happiness-edutainment.de/medien/34.jpg" /><p>Liebe Ausbildungsteilnehmerinnen und Ausbildungsteilnehmer!</p><p>Herzlich Willkommen im Ausbildungsprogramm zum Corporate Happiness® Botschafter! Wir freuen uns sehr, dass Sie den Weg auf die Plattform gefunden haben.  Im "Kurs 0" geht es zunächst darum, Sie für die Plattform fit zu machen und Ihnen einige Tipps und Tricks mit auf den Weg zu geben. So wird Ihnen die Arbeit auf der Plattform deutlich mehr Spaß machen. Sobald Sie diesen Kurs bearbeitet haben, können Sie mit den spannenden Inhalten beginnen und lernen, wie Sie Ihr Leben und das Ihrer Mitmenschen mit mehr Happiness bereichern können.</p><p>Wir wünschen Ihnen viel Spaß beim Durchklicken der ersten informativen Videos! Ihr Team von Corporate Happiness®</p>` },
  // { title: '0.1.1 Aufbau Ausbildungsprogramm', post_content: `<img class="alignnone size-full" src="https://happiness-edutainment.de/medien/34.jpg" alt="" />\n\nSie haben sich vielleicht schon gewundert, warum unsere Ausbildung im „Blended-Learning“ Format aufgebaut ist und es einen Wechsel aus Präsenz und Lernplattform gibt. Vielleicht haben Sie sich auch schon gefragt: „Reichen die Präsenztage nicht aus? Das macht doch viel mehr Spaß…“. Wir haben für Sie im folgenden Video zusammengefasst, was der Hintergrund von Blended-Learning ist und warum wir der Meinung sind, dass es nachhaltiges Lernen fördert und somit den Erfolg Ihrer Ausbildung sichert.\n\n[mycred_video id="173459160"]\n` },
  // { title: '0.1.2 Zurechtfinden auf der Plattform', post_content: `<p><img class="alignnone size-full" src="https://happiness-edutainment.de/medien/91.jpg" alt="" /></p>\n<p>Wo Sie was auf der Plattform finden, wie Sie Ihr Profil ändern und ein Profilbild hochladen können, wie Sie Nachrichten verfassen können, Forenbeiträge abonnieren können und noch vielen mehr, erfahren Sie im folgenden Video. Viel Spaß beim Entdecken der Plattform und ihrer Möglichkeiten!</p>\n<p><strong>Aufgabe: </strong><br />Da Sie ja jetzt wissen, wie Sie ihr Profil ändern und ein Bild hochladen können, laden wir Sie herzlich dazu ein es gleich mal auszuprobieren.</p>\n\n\n<figure class="wp-block-embed-vimeo wp-block-embed is-type-video is-provider-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps://vimeo.com/173470153\n</div></figure>\n` },
  // { title: '0.1.3 Erfolgs-Tipps für die Ausbildung', post_content: `<p><img class="alignnone size-full" src="https://happiness-edutainment.de/medien/35.jpg" alt="" /></p>\n<p>Bevor Sie nun endlich mit den Inhalten der Plattform beginnen können – Sie sind bestimmt schon voller Vorfreude – möchten wir Ihnen noch ein paar Tipps mit auf den Weg geben, wie Sie die Inhalte auf der Lernplattform erfolgreich und ohne Stress bearbeiten können und für jede Präsenz bestens vorbereitet sind! Jeder von uns kennt „den inneren Schweinehund“. Wir möchten Ihnen hier auf den Weg geben, wie Sie ihn bezwingen können und vor allem, wie Sie Ihre Zeit am besten einteilen.</p>\n\n\n<figure class="wp-block-embed-vimeo wp-block-embed is-type-video is-provider-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps://vimeo.com/173463849\n</div></figure>\n\n\n\n<figure class="wp-block-embed-vimeo wp-block-embed is-type-video is-provider-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">\nhttps://vimeo.com/173465532\n</div></figure>\n` },
]
coha.run();
